# Generated by Django 5.1.7 on 2025-03-27 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodtracker', '0002_remove_mood_user_id_mood_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='mood',
            name='anonymous_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
