# Generated by Django 5.1.7 on 2025-04-09 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodtracker', '0003_mood_anonymous_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mood',
            name='emotion_accuracy_confirmed',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True),
        ),
    ]
