# Generated by Django 5.2 on 2025-04-24 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodtracker', '0004_mood_emotion_accuracy_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='mood',
            name='advice',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mood',
            name='anonymous_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
