# Generated by Django 5.2 on 2025-04-24 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodtracker', '0005_mood_advice_alter_mood_anonymous_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mood',
            name='emotion_accuracy_confirmed',
        ),
        migrations.RemoveField(
            model_name='mood',
            name='mood',
        ),
        migrations.AddField(
            model_name='mood',
            name='emotion',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='mood',
            name='notes',
            field=models.TextField(default='unknown'),
            preserve_default=False,
        ),
    ]
