# Generated by Django 5.2 on 2025-04-24 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodtracker', '0006_remove_mood_emotion_accuracy_confirmed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mood',
            name='podcast_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mood',
            name='song_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
